name: Build Android Version

on:
  workflow_dispatch:

jobs:

  buildEnvAndSetUpAppApk:
    runs-on: ubuntu-latest

    steps:
      # Check out the code
      - uses: actions/checkout@v4

      # Pull the custom Docker image
      - name: Pull custom Docker image
        run: |
          docker pull ghcr.io/alexjyong/babbypaint:main

      # Prepare environment and build the Cordova apk file
      - name: Prepare environment and build
        run: |
          echo $JKS_KEYSTORE_BASE64 > upload-keystore.jks.b64
          base64 -d upload-keystore.jks.b64 > upload-keystore.jks
          mv upload-keystore.jks src/
          docker run --rm -i -v $PWD:/workspace -w /workspace --privileged ghcr.io/alexjyong/babbypaint:main sh -c "
            rm -rf .github &&
            cd src &&
            cordova build android --release -- --keystore=/workspace/src/upload-keystore.jks --storePassword=$KEYSTORE_PASSWORD --alias=uploadkey --password=$ALIAS_PASSWORD --packageType=apk"
        env:
          ALIAS_PASSWORD: ${{ secrets.ALIAS_PASSWORD }}
          JKS_KEYSTORE_BASE64: ${{ secrets.JKS_KEYSTORE_BASE64 }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}

      # Find and move the built APK file to the workspace
      - name: Move APK file
        run: |
          APK_PATH=$(find src -name '*.apk')
          if [ -z "$APK_PATH" ]; then
            echo "No APK file found!"
            exit 1
          fi
          sudo mkdir -p /workspace/apk
          sudo mv "$APK_PATH" /workspace/apk/

      # Upload the built APK file as an artifact
      - uses: actions/upload-artifact@v4
        with:
          name: babby-paint-apk-file
          path: /workspace/apk/*.apk
          
  buildEnvAndSetUpAppAbb:
    runs-on: ubuntu-latest

    steps:
      # Check out the code
      - uses: actions/checkout@v4

      # Pull the custom Docker image
      - name: Pull custom Docker image
        run: |
          docker pull ghcr.io/alexjyong/babbypaint:main

      # Prepare environment and build the babbypaint aab file
      - name: Prepare environment and build
        run: |
          echo $JKS_KEYSTORE_BASE64 > upload-keystore.jks.b64
          base64 -d upload-keystore.jks.b64 > upload-keystore.jks
          mv upload-keystore.jks src/
          docker run --rm -i -v $PWD:/workspace -w /workspace --privileged ghcr.io/alexjyong/babbypaint:main sh -c "
            rm -rf .github &&
            cd src &&
            cordova build android --release -- --keystore=/workspace/src/upload-keystore.jks --storePassword=$KEYSTORE_PASSWORD --alias=uploadkey --password=$ALIAS_PASSWORD --packageType=bundle"
        env:
          ALIAS_PASSWORD: ${{ secrets.ALIAS_PASSWORD }}
          JKS_KEYSTORE_BASE64: ${{ secrets.JKS_KEYSTORE_BASE64 }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}


      # Find and move the built aab file to the workspace
      - name: Move AAB file
        run: |
          AAB_PATH=$(find src -name '*app-release.aab')
          if [ -z "$AAB_PATH" ]; then
            echo "No AAB file found!"
            exit 1
          fi
          sudo mkdir -p /workspace/aab
          sudo mv "$AAB_PATH" /workspace/aab/

      # Upload the built aab file as an artifact
      - uses: actions/upload-artifact@v4
        with:
          name: babby-paint-aab-file
          path: /workspace/aab/*.aab
