name: Build Android Version

on:
  workflow_dispatch:

jobs:

  buildEnvAndSetUpAppApk:
    runs-on: ubuntu-latest

    steps:
      # Check out the code
      - uses: actions/checkout@v4

      # Pull the custom Docker image
      - name: Pull custom Docker image
        run: |
          docker pull ghcr.io/alexjyong/babbypaint:main

      # Prepare environment and build the Cordova apk file
      - name: Prepare environment and build
        run: |
          echo $JKS_KEYSTORE_BASE64 > upload-keystore.jks.b64
          base64 -d upload-keystore.jks.b64 > upload-keystore.jks
          mv upload-keystore.jks src/
          docker run --rm -i -v $PWD:/workspace -w /workspace --privileged ghcr.io/alexjyong/babbypaint:main sh -c "
            rm -rf .github &&
            cd src &&
            rm -rf platforms/android
            rm -rf plugins
            cordova platform add android --verbose &&
            cordova plugin add cordova-plugin-x-toast &&
            cordova plugin add cordova-plugin-screen-pinning --verbose &&
            cordova build android --release -- --keystore=/workspace/src/upload-keystore.jks --storePassword=$KEYSTORE_PASSWORD --alias=uploadkey --password=$ALIAS_PASSWORD --packageType=apk
            jarsigner -verbose -keystore /workspace/src/upload-keystore.jks \
            -storepass $KEYSTORE_PASSWORD \
            -keypass $ALIAS_PASSWORD \
            /workspace/src/platforms/android/app/build/outputs/apk/release/app-release.apk \
            uploadkey"
        env:
          ALIAS_PASSWORD: ${{ secrets.ALIAS_PASSWORD }}
          JKS_KEYSTORE_BASE64: ${{ secrets.JKS_KEYSTORE_BASE64 }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
      

      # Verify the APK signature using apksigner
      - name: Verify APK signature
        run: |
          docker run --rm -v $PWD:/workspace -w /workspace --privileged ghcr.io/alexjyong/babbypaint:main sh -c "
            jarsigner -verify -verbose -certs /workspace/src/platforms/android/app/build/outputs/apk/release/app-release.apk"
      
      # Upload the built APK file as an artifact
      - uses: actions/upload-artifact@v4
        with:
          name: babby-paint-apk-file
          path: /workspace/src/platforms/android/app/build/outputs/apk/release/app-release.apk

  buildEnvAndSetUpAppAab:
    runs-on: ubuntu-latest

    steps:
      # Check out the code
      - uses: actions/checkout@v4

      # Pull the custom Docker image
      - name: Pull custom Docker image
        run: |
          docker pull ghcr.io/alexjyong/babbypaint:main

      # Prepare environment and build the babbypaint aab file
      - name: Prepare environment and build
        run: |
          echo $JKS_KEYSTORE_BASE64 > upload-keystore.jks.b64
          base64 -d upload-keystore.jks.b64 > upload-keystore.jks
          mv upload-keystore.jks src/
          docker run --rm -i -v $PWD:/workspace -w /workspace --privileged ghcr.io/alexjyong/babbypaint:main sh -c "
            rm -rf .github &&
            cd src &&
            rm -rf platforms/android
            rm -rf plugins
            cordova platform add android --verbose &&
            cordova plugin add cordova-plugin-x-toast &&
            cordova plugin add cordova-plugin-screen-pinning --verbose &&
            cordova build android --release -- --keystore=/workspace/src/upload-keystore.jks --storePassword=$KEYSTORE_PASSWORD --alias=uploadkey --password=$ALIAS_PASSWORD --packageType=bundle"
        env:
          ALIAS_PASSWORD: ${{ secrets.ALIAS_PASSWORD }}
          JKS_KEYSTORE_BASE64: ${{ secrets.JKS_KEYSTORE_BASE64 }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}

      # Manually sign the AAB using jarsigner
      - name: Manually sign the AAB
        run: |
          docker run --rm -v $PWD:/workspace -w /workspace --privileged ghcr.io/alexjyong/babbypaint:main sh -c "
            jarsigner -verbose -keystore /workspace/src/upload-keystore.jks -storepass $KEYSTORE_PASSWORD -keypass $ALIAS_PASSWORD /workspace/src/platforms/android/app/build/outputs/bundle/release/app-release.aab uploadkey"
        env:
          ALIAS_PASSWORD: ${{ secrets.ALIAS_PASSWORD }}
          JKS_KEYSTORE_BASE64: ${{ secrets.JKS_KEYSTORE_BASE64 }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}

      # Verify the AAB signature using jarsigner
      - name: Verify AAB signature
        run: |
          docker run --rm -v $PWD:/workspace -w /workspace --privileged ghcr.io/alexjyong/babbypaint:main sh -c "
            jarsigner -verify -verbose -certs /workspace/src/platforms/android/app/build/outputs/bundle/release/app-release.aab"


      # Upload the built AAB file as an artifact
      - uses: actions/upload-artifact@v4
        with:
          name: babby-paint-aab-file
          path: /workspace/src/platforms/android/app/build/outputs/bundle/release/app-release.aab
