name: Build Android Version

on:
  workflow_dispatch:

jobs:
  buildEnvAndSetUpApp:
    runs-on: ubuntu-latest

    steps:
      # Check out the code
      - uses: actions/checkout@v4

      # Pull the custom Docker image
      - name: Pull custom Docker image
        run: |
          docker pull ghcr.io/alexjyong/babbypaint:main

      # Prepare environment and build the Cordova app
      - name: Prepare environment and build
        run: |
          docker run --rm -i -v $PWD:/workspace -w /workspace --privileged babby-paint sh -c "
            rm -rf .github &&
            cd src &&
            cordova platform add android &&
            cordova plugin add cordova-plugin-screen-pinning &&
            cordova build"

      # Find and move the built APK file to the workspace
      - name: Move APK file
        run: |
          APK_PATH=$(find src -name '*.apk')
          if [ -z "$APK_PATH" ]; then
            echo "No APK file found!"
            exit 1
          fi
          sudo mkdir -p /workspace/apk
          sudo mv "$APK_PATH" /workspace/apk/

      # Upload the built APK file as an artifact
      - uses: actions/upload-artifact@v4
        with:
          name: babby-paint-apk-file
          path: /workspace/apk/*.apk
